### ISSUE TITLE
Hosting best-known solutions of benchmark instances

### ISSUE THREAD

**Issue by leonlan** [ai-for-decision-making-tue/Job_Shop_Scheduling_Benchmark_Environments_and_Instances#2]
Hi all, just came across this library by coincidence. Great to see this effort to make a benchmark repository! I'm working on flexible job shop scheduling problems and flow shop problems for my own research. 

One major difficulty I have is that most papers/repositories don't store their solutions but only report the best-found value. This makes it hard to verify their results. In vehicle routing, we have e.g., [CVRPLIB](vrp.atd-lab.inf.puc-rio.br/index.php/en/) which maintains the best-known solutions for CVRP and VRPTW. We also try to do that for prize-collecting VRP [here](https://github.com/PyVRP/Instances/tree/eacd9b1d7abbca2d93ae988af503fad7b02dd530/PC-VRPTW).

Are there any plans from your side to host the best-known solutions? Happy to contribute as well.

**Comment by RobbertReijnen** [comment]
Hi, thanks for reaching out! We are definitely considering this, as it would also be a very natural step forward for this project.
I would like to hear your thoughts on this - I will reach out to you via email.

Best,
Robbert
