### ISSUE TITLE
你好，请问应该用哪个python版本呢？

### ISSUE THREAD

**Issue by Unsurefeedback** [ai-for-decision-making-tue/Job_Shop_Scheduling_Benchmark_Environments_and_Instances#24]
我用py3.12的环境，有些包安装不了。

**Comment by RobbertReijnen** [comment]
Hi - We have tested only with 3.10 and 3.11 so far (see PR). Will test it with 3.12 soon. Have you encountered problems while running 3.12?

**Comment by Unsurefeedback** [comment]
Thanks! Switching back to Python version 3.10 allowed me to run the code successfully.
