### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Oceanwhyd** [ai-for-decision-making-tue/Job_Shop_Scheduling_Benchmark_Environments_and_Instances#36]
Can you tell me where that the fajsp data comes from ：）

**Comment by RobbertReijnen** [comment]
Hi, thanks for showing interest in the project!

The both the problem variants for fajsp are coming from: 
Ernesto G Birgin, Paulo Feofiloff, Cristina G Fernandes, Everton L De Melo, Marcio TI Oshiro, and D´ebora P Ronconi. A milp model for an extended version of the flexible job shop problem. Optimization Letters, 8:1417–1431, 2014.

**Comment by Oceanwhyd** [comment]
Thank you for your response, and also for your public project! :-)

**Comment by RobbertReijnen** [comment]
I'm glad to hear that you appreciate our work :-).

We will update the paper of the work shortly (hopefully within 2 weeks). In the paper, we will include all the references to the solution methods/data resources, and will also provide best-known/optimal solution values on the different instances used in the work.

In the meantime, if you find our repository helpful or interesting, we would greatly appreciate it if you could star it, helping others to discover our work as well. 😊
